#!/bin/sh
if [ ! -z "$1" ] ;then
clear


COMPILER=/home/JB/GPL_toolchains/bin/arm-eabi-
#COMPILER=/home/JB/Downloads/android-toolchain-eabi/bin/arm-eabi-
. runhtc $COMPILER shooter_u_BOTH_defconfig anryl g$1
. runhtc $COMPILER shooter_u_LZO_defconfig anryl l$1
. runhtc $COMPILER shooter_u_LZ4_defconfig anryl l4$1
. runhtc $COMPILER shooter_u_XZ_defconfig anryl x$1
if [ ! -z "$2" ] ;then
cp include/media/~evmsm_camera.h include/media/msm_camera.h
. runhtc $COMPILER shooter_u_LZO_defconfig anryl el$1
cp include/media/~orig_msm_camera.h include/media/msm_camera.h
fi
#. runhtc $COMPILER shooter_u_BOTHTHERM_defconfig therm $1
#. runhtc $COMPILER shooter_u_SBCM_defconfig HTCBCM $1
#. runhtc $COMPILER shooter_u_SDHD_defconfig HTCDHD $1
#. runhtc $COMPILER shooter_u_OTG_defconfig OTG $1
#. runhtc $COMPILER shooter_u_OTGOC_defconfig OTGOC $1
fi
